-- GymTracker SQLite schema - version 1.
-- Source of truth: docs/ARCHITECTURE.md section 7. Applied as migration 001_initial
-- (database/migrations/001_initial.ts). Do not edit this file and the migration
-- separately - the migration executes exactly this file's statements, see that
-- module's own comment for how the two are kept in sync.
--
-- Global conventions (ARCHITECTURE.md 7.1): TEXT UUIDv7 primary keys, INTEGER epoch
-- millisecond timestamps (+ local_date TEXT where a row belongs to a calendar day),
-- INTEGER booleans constrained to (0,1), REAL kg / REAL cm canonical units, soft
-- delete via deleted_at on user-owned tables, created_at/updated_at on every
-- user-owned table.

-- ============================================================================
-- 7.2 Migration infrastructure
-- ============================================================================

-- Schema version is tracked by PRAGMA user_version (integer).
-- This table exists for human-readable diagnostics and export metadata.
CREATE TABLE migration_history (
    version     INTEGER PRIMARY KEY,
    name        TEXT    NOT NULL,
    applied_at  INTEGER NOT NULL,
    app_version TEXT    NOT NULL
);

-- ============================================================================
-- 7.3 Profile and settings
-- ============================================================================

CREATE TABLE user_profile (
    id                TEXT PRIMARY KEY,            -- always 'local'
    nickname          TEXT NOT NULL,
    avatar_file_name  TEXT,                        -- relative name inside avatars/, never an absolute URI
    birth_date        TEXT,                        -- YYYY-MM-DD, optional, used for calorie estimates
    sex               TEXT CHECK (sex IN ('male','female','unspecified')),
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL
);

CREATE TABLE app_setting (
    key        TEXT PRIMARY KEY,
    value      TEXT    NOT NULL,   -- JSON scalar or object, validated by a per-key Zod schema
    updated_at INTEGER NOT NULL
);

-- ============================================================================
-- 7.4 Exercise catalog
-- ============================================================================

CREATE TABLE muscle (
    slug      TEXT PRIMARY KEY,      -- 'chest', 'lats', 'quadriceps', ...
    name_en   TEXT NOT NULL,
    name_pl   TEXT,
    body_part TEXT NOT NULL,         -- 'upper','lower','core','arms','back','shoulders','legs'
    sort_order INTEGER NOT NULL
);

CREATE TABLE equipment (
    slug     TEXT PRIMARY KEY,       -- 'barbell','dumbbell','machine','cable','body only', ...
    name_en  TEXT NOT NULL,
    name_pl  TEXT,
    is_gym   INTEGER NOT NULL DEFAULT 1 CHECK (is_gym IN (0,1)),
    is_home  INTEGER NOT NULL DEFAULT 0 CHECK (is_home IN (0,1)),
    sort_order INTEGER NOT NULL
);

CREATE TABLE exercise (
    id             TEXT PRIMARY KEY,
    source         TEXT NOT NULL CHECK (source IN ('catalog','custom')),
    catalog_slug   TEXT UNIQUE,                     -- free-exercise-db id; NULL for custom
    name_en        TEXT NOT NULL,
    name_pl        TEXT,
    name_search    TEXT NOT NULL,                   -- lowercased, diacritics folded, en + pl + aliases
    aliases        TEXT NOT NULL DEFAULT '[]',      -- JSON array of alternative names
    category       TEXT,                            -- strength, stretching, plyometrics, powerlifting, ...
    force          TEXT CHECK (force IS NULL OR force IN ('push','pull','static')),
    mechanic       TEXT CHECK (mechanic IS NULL OR mechanic IN ('compound','isolation')),
    level          TEXT CHECK (level IS NULL OR level IN ('beginner','intermediate','expert')),
    equipment_slug TEXT REFERENCES equipment(slug) ON DELETE SET NULL,
    body_part      TEXT,
    tracking_type  TEXT NOT NULL DEFAULT 'weight_reps'
                   CHECK (tracking_type IN ('weight_reps','reps_only','duration','distance_duration','weighted_duration')),
    instructions   TEXT NOT NULL DEFAULT '[]',      -- JSON array of paragraphs
    images          TEXT NOT NULL DEFAULT '[]',      -- JSON array of bundled asset keys
    created_at     INTEGER NOT NULL,
    updated_at     INTEGER NOT NULL,
    deleted_at     INTEGER
);

CREATE TABLE exercise_user_data (
    exercise_id          TEXT PRIMARY KEY REFERENCES exercise(id) ON DELETE CASCADE,
    is_favorite          INTEGER NOT NULL DEFAULT 0 CHECK (is_favorite IN (0,1)),
    favorited_at         INTEGER,
    note                 TEXT,
    default_rest_seconds INTEGER CHECK (default_rest_seconds IS NULL OR default_rest_seconds BETWEEN 5 AND 1800),
    display_name_override TEXT,
    last_performed_at    INTEGER,                   -- denormalized, maintained on session finish
    created_at           INTEGER NOT NULL,
    updated_at           INTEGER NOT NULL
);

CREATE TABLE exercise_muscle (
    exercise_id TEXT NOT NULL REFERENCES exercise(id) ON DELETE CASCADE,
    muscle_slug TEXT NOT NULL REFERENCES muscle(slug) ON DELETE CASCADE,
    role        TEXT NOT NULL CHECK (role IN ('primary','secondary')),
    PRIMARY KEY (exercise_id, muscle_slug, role)
) WITHOUT ROWID;

CREATE TABLE exercise_video (
    id          TEXT PRIMARY KEY,
    exercise_id TEXT NOT NULL REFERENCES exercise(id) ON DELETE CASCADE,
    url         TEXT NOT NULL,
    title       TEXT NOT NULL,
    channel     TEXT,                                -- 'Jeff Nippard', 'Squat University', ...
    language    TEXT NOT NULL DEFAULT 'en' CHECK (language IN ('en','pl')),
    source      TEXT NOT NULL DEFAULT 'curated' CHECK (source IN ('curated','user')),
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL,
    deleted_at  INTEGER
);

-- Full-text search (FR-06, NFR-03).
CREATE VIRTUAL TABLE exercise_fts USING fts5(
    name_en,
    name_pl,
    aliases,
    equipment_slug,
    muscles,                                  -- denormalized space-joined muscle slugs
    content = '',                             -- contentless: we store only the index
    tokenize = "unicode61 remove_diacritics 2"
);
-- Populated and maintained by the ExerciseRepository inside the same transaction as
-- any exercise write, and rebuilt wholesale by the catalog seeder. Triggers are
-- deliberately not used: the muscles column is derived from a join, which a row
-- trigger on `exercise` cannot see consistently.

-- ============================================================================
-- 7.5 Plans
-- ============================================================================

CREATE TABLE plan (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    color       TEXT,                                  -- token key, e.g. 'accent', 'chart.2'
    is_active   INTEGER NOT NULL DEFAULT 0 CHECK (is_active IN (0,1)),
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL,
    deleted_at  INTEGER
);

-- At most one active plan, enforced by the database rather than by application code.
CREATE UNIQUE INDEX ux_plan_single_active
    ON plan (is_active) WHERE is_active = 1 AND deleted_at IS NULL;

CREATE TABLE plan_day (
    id         TEXT PRIMARY KEY,
    plan_id    TEXT NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,                          -- 'Upper A', 'Push', ...
    note       TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    deleted_at INTEGER
);

CREATE TABLE plan_day_exercise (
    id                 TEXT PRIMARY KEY,
    plan_day_id        TEXT NOT NULL REFERENCES plan_day(id) ON DELETE CASCADE,
    exercise_id        TEXT NOT NULL REFERENCES exercise(id) ON DELETE RESTRICT,
    sort_order         INTEGER NOT NULL DEFAULT 0,
    target_sets        INTEGER CHECK (target_sets IS NULL OR target_sets BETWEEN 1 AND 50),
    target_rep_min     INTEGER,
    target_rep_max     INTEGER,
    target_rpe         REAL CHECK (target_rpe IS NULL OR target_rpe BETWEEN 1 AND 10),
    rest_seconds       INTEGER,
    superset_group     INTEGER,                        -- NULL = standalone; equal values = supersetted
    note               TEXT,
    created_at         INTEGER NOT NULL,
    updated_at         INTEGER NOT NULL,
    deleted_at         INTEGER,
    CHECK (target_rep_min IS NULL OR target_rep_max IS NULL OR target_rep_min <= target_rep_max)
);

-- ============================================================================
-- 7.6 Workout sessions - the core write path
-- ============================================================================

CREATE TABLE workout_session (
    id                      TEXT PRIMARY KEY,
    plan_id                 TEXT REFERENCES plan(id) ON DELETE SET NULL,
    plan_day_id             TEXT REFERENCES plan_day(id) ON DELETE SET NULL,
    plan_name_snapshot      TEXT,                       -- history survives plan deletion
    plan_day_name_snapshot  TEXT,
    title                   TEXT NOT NULL,
    status                  TEXT NOT NULL DEFAULT 'in_progress'
                            CHECK (status IN ('in_progress','completed','discarded')),
    started_at              INTEGER NOT NULL,
    finished_at             INTEGER,
    local_date              TEXT NOT NULL,              -- YYYY-MM-DD, user timezone at start
    tz_offset_minutes       INTEGER NOT NULL,
    duration_seconds        INTEGER,                    -- denormalized on finish, excludes paused time
    paused_ms               INTEGER NOT NULL DEFAULT 0,
    total_volume_kg         REAL,                        -- denormalized on finish
    total_sets              INTEGER,
    total_reps              INTEGER,
    estimated_kcal          INTEGER,
    notes                   TEXT,
    created_at              INTEGER NOT NULL,
    updated_at              INTEGER NOT NULL,
    deleted_at              INTEGER,
    CHECK (status <> 'completed' OR finished_at IS NOT NULL)
);

-- FR-19 guard: the app can never end up with two in-progress workouts.
CREATE UNIQUE INDEX ux_session_single_in_progress
    ON workout_session (status) WHERE status = 'in_progress';

CREATE TABLE session_exercise (
    id                     TEXT PRIMARY KEY,
    session_id             TEXT NOT NULL REFERENCES workout_session(id) ON DELETE CASCADE,
    exercise_id            TEXT NOT NULL REFERENCES exercise(id) ON DELETE RESTRICT,
    exercise_name_snapshot TEXT NOT NULL,
    sort_order             INTEGER NOT NULL DEFAULT 0,
    superset_group         INTEGER,
    rest_seconds_override  INTEGER,
    note                   TEXT,
    created_at             INTEGER NOT NULL,
    updated_at             INTEGER NOT NULL,
    deleted_at             INTEGER
);

CREATE TABLE workout_set (
    id                  TEXT PRIMARY KEY,
    session_exercise_id TEXT NOT NULL REFERENCES session_exercise(id) ON DELETE CASCADE,
    session_id          TEXT NOT NULL REFERENCES workout_session(id) ON DELETE CASCADE,  -- denormalized
    exercise_id         TEXT NOT NULL REFERENCES exercise(id) ON DELETE RESTRICT,        -- denormalized
    set_index           INTEGER NOT NULL,                -- 1-based within session_exercise
    set_type            TEXT NOT NULL DEFAULT 'normal'
                        CHECK (set_type IN ('warmup','normal','drop','failure','assisted','partial')),
    parent_set_id       TEXT REFERENCES workout_set(id) ON DELETE CASCADE,  -- drop-set chain
    weight_kg           REAL CHECK (weight_kg IS NULL OR weight_kg >= 0),
    reps                INTEGER CHECK (reps IS NULL OR reps BETWEEN 0 AND 1000),
    duration_seconds    INTEGER,
    distance_m          REAL,
    rpe                 REAL CHECK (rpe IS NULL OR rpe BETWEEN 1 AND 10),
    is_completed        INTEGER NOT NULL DEFAULT 0 CHECK (is_completed IN (0,1)),
    completed_at        INTEGER,
    performed_at        INTEGER NOT NULL,                -- ordering key for history queries
    note                TEXT,
    created_at          INTEGER NOT NULL,
    updated_at          INTEGER NOT NULL,
    deleted_at          INTEGER,
    CHECK (is_completed = 0 OR completed_at IS NOT NULL),
    CHECK (parent_set_id IS NULL OR set_type = 'drop')
);

-- FR-19 / FR-14: everything needed to restore the workout screen and the running
-- timer after process death. One row, existing only while a workout is in progress.
CREATE TABLE active_session_state (
    session_id             TEXT PRIMARY KEY REFERENCES workout_session(id) ON DELETE CASCADE,
    focused_session_exercise_id TEXT,
    timer_deadline_at      INTEGER,        -- absolute epoch ms; NULL when no timer runs
    timer_total_seconds    INTEGER,
    timer_notification_id  TEXT,           -- scheduled Expo notification, cancelled on early finish
    paused_at              INTEGER,
    scroll_offset          REAL,
    updated_at             INTEGER NOT NULL
);

-- ============================================================================
-- 7.7 Personal records
-- ============================================================================

CREATE TABLE personal_record (
    id             TEXT PRIMARY KEY,
    exercise_id    TEXT NOT NULL REFERENCES exercise(id) ON DELETE CASCADE,
    record_type    TEXT NOT NULL CHECK (record_type IN
                   ('max_weight','max_reps','weight_at_reps','max_set_volume',
                    'max_session_volume','estimated_1rm','max_duration','max_distance')),
    rep_bucket     INTEGER,          -- only for weight_at_reps (1,2,3,5,8,10,12); NULL otherwise
    value          REAL NOT NULL,    -- comparable magnitude for this record_type
    weight_kg      REAL,
    reps           INTEGER,
    workout_set_id TEXT REFERENCES workout_set(id) ON DELETE SET NULL,
    session_id     TEXT REFERENCES workout_session(id) ON DELETE SET NULL,
    achieved_at    INTEGER NOT NULL,
    previous_value REAL,
    is_current     INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0,1)),
    created_at     INTEGER NOT NULL,
    updated_at     INTEGER NOT NULL
);

CREATE UNIQUE INDEX ux_pr_current
    ON personal_record (exercise_id, record_type, IFNULL(rep_bucket, -1))
    WHERE is_current = 1;

-- ============================================================================
-- 7.8 Body measurements and progress photos
-- ============================================================================

CREATE TABLE body_metric_entry (
    id          TEXT PRIMARY KEY,
    metric      TEXT NOT NULL CHECK (metric IN
                ('body_weight','body_fat_pct','chest','waist','hips','neck','shoulders',
                 'arm_left','arm_right','forearm_left','forearm_right',
                 'thigh_left','thigh_right','calf_left','calf_right')),
    value       REAL NOT NULL,       -- kg for body_weight, percent for body_fat_pct, cm otherwise
    measured_at INTEGER NOT NULL,
    local_date  TEXT NOT NULL,
    note        TEXT,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL,
    deleted_at  INTEGER
);

CREATE TABLE progress_photo (
    id         TEXT PRIMARY KEY,
    file_name  TEXT NOT NULL UNIQUE,     -- relative to documentDirectory/progress-photos/
    thumb_name TEXT NOT NULL,
    pose       TEXT NOT NULL DEFAULT 'front' CHECK (pose IN ('front','side','back','other')),
    taken_at   INTEGER NOT NULL,
    local_date TEXT NOT NULL,
    width      INTEGER NOT NULL,
    height     INTEGER NOT NULL,
    byte_size  INTEGER NOT NULL,
    note       TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    deleted_at INTEGER
);

-- ============================================================================
-- 7.9 Indexes
-- ============================================================================

-- Hot path: previous performance and per-exercise progression charts.
CREATE INDEX ix_set_exercise_time     ON workout_set (exercise_id, performed_at DESC)
                                       WHERE deleted_at IS NULL AND is_completed = 1;
-- Hot path: rendering the active workout and any session detail.
CREATE INDEX ix_set_session           ON workout_set (session_id, set_index);
CREATE INDEX ix_set_session_exercise  ON workout_set (session_exercise_id, set_index);
CREATE INDEX ix_set_parent            ON workout_set (parent_set_id) WHERE parent_set_id IS NOT NULL;

-- History list, calendar, streaks, weekly summary.
CREATE INDEX ix_session_local_date    ON workout_session (local_date DESC)
                                       WHERE status = 'completed' AND deleted_at IS NULL;
CREATE INDEX ix_session_started       ON workout_session (started_at DESC);
CREATE INDEX ix_session_plan_day      ON workout_session (plan_day_id, started_at DESC);

CREATE INDEX ix_session_exercise_sess ON session_exercise (session_id, sort_order);
CREATE INDEX ix_session_exercise_ex   ON session_exercise (exercise_id, created_at DESC);

-- Library browsing and filtering.
CREATE INDEX ix_exercise_equipment    ON exercise (equipment_slug) WHERE deleted_at IS NULL;
CREATE INDEX ix_exercise_name         ON exercise (name_search)    WHERE deleted_at IS NULL;
CREATE INDEX ix_exercise_source       ON exercise (source)         WHERE deleted_at IS NULL;
CREATE INDEX ix_exercise_muscle_rev   ON exercise_muscle (muscle_slug, role);
CREATE INDEX ix_exercise_fav          ON exercise_user_data (is_favorite, favorited_at DESC)
                                       WHERE is_favorite = 1;
CREATE INDEX ix_video_exercise        ON exercise_video (exercise_id, sort_order) WHERE deleted_at IS NULL;

-- Plans.
CREATE INDEX ix_plan_day_plan         ON plan_day (plan_id, sort_order)  WHERE deleted_at IS NULL;
CREATE INDEX ix_pde_day               ON plan_day_exercise (plan_day_id, sort_order) WHERE deleted_at IS NULL;
CREATE INDEX ix_pde_exercise          ON plan_day_exercise (exercise_id) WHERE deleted_at IS NULL;

-- Records and measurements.
CREATE INDEX ix_pr_exercise           ON personal_record (exercise_id, record_type, achieved_at DESC);
CREATE INDEX ix_pr_recent             ON personal_record (achieved_at DESC) WHERE is_current = 1;
CREATE INDEX ix_body_metric           ON body_metric_entry (metric, measured_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX ix_photo_taken           ON progress_photo (taken_at DESC) WHERE deleted_at IS NULL;

-- ============================================================================
-- 7.10 Views (the read model)
-- ============================================================================

-- Every set that counts as work, with its volume already computed per the 6.3 rules.
CREATE VIEW v_working_set AS
SELECT ws.*,
       s.local_date,
       s.started_at AS session_started_at,
       CASE
         WHEN ws.set_type IN ('warmup','assisted','partial') THEN 0.0
         WHEN ws.weight_kg IS NULL OR ws.reps IS NULL        THEN 0.0
         ELSE ws.weight_kg * ws.reps
       END AS volume_kg
FROM workout_set ws
JOIN workout_session s ON s.id = ws.session_id
WHERE ws.deleted_at IS NULL
  AND ws.is_completed = 1
  AND s.deleted_at IS NULL
  AND s.status = 'completed';

-- Session-level aggregates without loading sets into JS.
CREATE VIEW v_session_summary AS
SELECT s.id, s.local_date, s.started_at, s.finished_at, s.duration_seconds,
       s.plan_day_name_snapshot,
       COUNT(DISTINCT vs.session_exercise_id) AS exercise_count,
       COUNT(vs.id)                           AS working_set_count,
       COALESCE(SUM(vs.volume_kg), 0)         AS total_volume_kg,
       COALESCE(SUM(vs.reps), 0)              AS total_reps
FROM workout_session s
LEFT JOIN v_working_set vs ON vs.session_id = s.id
WHERE s.deleted_at IS NULL AND s.status = 'completed'
GROUP BY s.id;

-- "Previous performance" for the active workout screen.
CREATE VIEW v_exercise_last_session AS
SELECT exercise_id, session_id, MAX(performed_at) AS performed_at
FROM v_working_set
GROUP BY exercise_id;
