/**
 * Build-time exercise image lookup generator.
 *
 * Metro needs a static, literal `require('./some/file.webp')` call per asset it
 * bundles - a dynamic `require(variablePath)` is not statically analyzable and
 * will not resolve at build time. The exercise catalog
 * (`assets/data/exercises.catalog.json`) references bundled images by bare
 * filename (e.g. `"26e9975d65f43036.webp"`), read at runtime from SQLite, so
 * something has to bridge "runtime string key" to "build-time literal require".
 * This script is that bridge: it walks `assets/exercises/`, one `require(...)`
 * literal per file, and writes them into a single generated lookup module.
 *
 *   assets/exercises/imageMap.ts   generated, never hand-edited
 *
 * Deterministic and idempotent: sorted key order, no embedded timestamps, no
 * non-deterministic ordering - re-running against an unchanged `assets/exercises/`
 * directory produces a byte-identical file (reviewable with `git diff --stat`),
 * matching the convention `scripts/build-catalog.ts` already uses for
 * `exercises.catalog.json`.
 *
 * Run manually whenever the bundled image set changes (a re-run of
 * `scripts/build-catalog.ts`, or any other addition/removal under
 * `assets/exercises/`) - not part of the app's own build or test suite.
 *
 * Usage: npm run build:exercise-images
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const IMAGES_DIR = path.join(REPO_ROOT, 'assets', 'exercises');
const OUTPUT_PATH = path.join(IMAGES_DIR, 'imageMap.ts');

const IMAGE_EXTENSIONS = new Set(['.webp', '.png', '.jpg', '.jpeg']);

/**
 * A bare filename becomes a valid single-quoted JS string key and a valid
 * relative `require` specifier as-is (the catalog build pipeline only ever
 * emits `<16-hex-char-hash>.webp`), so no escaping beyond wrapping in quotes
 * is needed. Guard against anything that would break that assumption instead
 * of silently emitting broken output.
 */
function assertSafeFilename(filename: string): void {
  if (!/^[A-Za-z0-9._-]+$/.test(filename)) {
    throw new Error(
      `Unsafe filename "${filename}" in ${path.relative(REPO_ROOT, IMAGES_DIR)} - expected only ` +
        `letters, digits, ".", "_", "-". Refusing to emit a require() for it.`,
    );
  }
}

function readImageFilenames(): string[] {
  const entries = fs.readdirSync(IMAGES_DIR, { withFileTypes: true });
  const filenames = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase()));

  for (const name of filenames) assertSafeFilename(name);

  return filenames.sort((a, b) => a.localeCompare(b));
}

function renderModule(filenames: readonly string[]): string {
  const entries = filenames
    .map((name) => `  '${name}': require('./${name}') as ImageSourcePropType,`)
    .join('\n');

  return `/**
 * AUTO-GENERATED by scripts/build-exercise-image-map.ts - do not hand-edit.
 * Regenerate with: npm run build:exercise-images
 *
 * One literal require() call per bundled exercise image (Metro cannot resolve
 * a dynamic require(variablePath) at build time - see the generator script's
 * header comment for the full rationale). Keyed by the bare filename the
 * exercise catalog references in its images array
 * (assets/data/exercises.catalog.json), e.g. "26e9975d65f43036.webp".
 *
 * Do not import this map directly from feature code - use
 * getExerciseImageSource from assets/exercises/index.ts instead.
 */
import type { ImageSourcePropType } from 'react-native';

export const exerciseImageMap: Record<string, ImageSourcePropType> = {
${entries}
};

export const exerciseImageFilenameCount = ${filenames.length};
`;
}

function main(): void {
  fs.mkdirSync(IMAGES_DIR, { recursive: true });

  const filenames = readImageFilenames();
  if (filenames.length === 0) {
    throw new Error(`No image files found in ${path.relative(REPO_ROOT, IMAGES_DIR)}`);
  }

  const seen = new Set<string>();
  for (const name of filenames) {
    if (seen.has(name)) {
      throw new Error(`Duplicate filename "${name}" - readdir should never repeat an entry`);
    }
    seen.add(name);
  }

  const moduleSource = renderModule(filenames);
  fs.writeFileSync(OUTPUT_PATH, moduleSource);

  console.log(
    `[build-exercise-image-map] wrote ${filenames.length} entries to ${path.relative(REPO_ROOT, OUTPUT_PATH)}`,
  );
}

main();
